# Generated by Django 4.0.5 on 2022-10-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alert_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='range',
        ),
        migrations.AddField(
            model_name='alert',
            name='exchange_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, verbose_name='알림 설정시 환율 가격'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='알림 요청 가격'),
        ),
    ]
