version: "3.8"

services:
  django:
    &django
    container_name: "exchange_rate"
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: dockerfile
    restart: always
    expose:
      - 8000
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: dockerfile
    # image: nginx_django:1.19.0-alpine
    restart: always
    ports:
      - 80:80
    depends_on:
    - django

  postgres:
    container_name: "postgres"
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # celery_worker:
  #   <<: *django
  #   container_name: "celery_worker"
  #   command: celery -A config worker --loglevel=info
  #   depends_on:
  #     - postgres
  # celery_beat:
  #   <<: *django
  #   container_name: "celery_beat"
  #   # image: django
  #   command: celery -A backend beat --loglevel=info
  #   depends_on:
  #     - postgres
