version: "3.8"

services:
  django:
    container_name: exchange_rate
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - ./backend/.env
    restart: always
    expose:
      - 8000

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: dockerfile
    image: nginx_django:1.19.0-alpine
    restart: always
    ports:
      - 80:80
    depends_on:
    - django
