version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: exchange_rate:0.0.1
    container_name: exchange_rate
    restart: always
    ports:
      - 8000:8000
    