version: "3.8"

services:
  django:
    container_name: exchange_rate
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: exchange_rate:0.0.2
    restart: always
    expose:
      - 8000

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx_django:1.19.0-alpine
    restart: always
    ports:
      - 80:80
    depends_on:
    - django
