version: "3.8"

services:
  django:
    container_name: exchange_rate
    image: ${DJANGO_IMAGE}:${DJANGO_TAG}
    restart: always
    expose:
      - 8000

  nginx:
    container_name: nginx
    image: ${NAINX_IMAGE}:${NGINX_TAG}
    restart: always
    ports:
      - 80:80
    depends_on:
    - django
