version: "3.8"

services:
  django:
    container_name: exchange_rate
    env_file:
      - ./.env
    # image: ${DJANGO_IMAGE}:${DJANGO_TAG}
    image: hub.1ife.kr/exchange-rate:0.3.0
    restart: always
    expose:
      - 8000
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    # image: ${NGINX_IMAGE}:${NGINX_TAG}
    image: hub.1ife.kr/nginx:0.1.0
    restart: always
    ports:
      - 80:80
    depends_on:
      - django

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  celery_worker:
    container_name: celery_worker
    image: django
    volumes: -./:/home/
    command: celery -A backend worker --loglevel=info

  celery_beat:
    container_name: celery_beat
    command: celery -A backend beat --loglevel=info
