FROM python:3.9-slim

WORKDIR /app

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# RUN apk update && apk add bash

RUN pip install --upgrade pip

RUN ls -al
RUN pip install -r requirements.txt

EXPOSE 8000

COPY . .

# ADD USER
# RUN adduser -u 8080 --disabled-password --gecos "" exchange-rate && chown -R exchange-rate /app
# USER exchange-rate 

CMD ["gunicorn", "config.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "--access-logfile", "./gunicorn-access.log", "--bind", "0.0.0.0:8000"]

