FROM python:3.9-alpine 

WORKDIR /app

RUN apk update && apk add bash

RUN pip install --upgrade pip

RUN pip install --user -r prod.txt

EXPOSE 8000

COPY . .

# ADD USER
# RUN adduser -u 8080 --disabled-password --gecos "" exchange-rate && chown -R exchange-rate /app
# USER exchange-rate 

CMD ["gunicorn", "config.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "--access-logfile", "./gunicorn-access.log", "--bind", "0.0.0.0:8000"]

