FROM  hub.1ife.kr/python:3.10.4-slim

# Keeps Python from generating .pyc files in the container
# ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
# ENV PYTHONUNBUFFERED=1

WORKDIR /app

EXPOSE 8000

COPY . .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

# ADD USER
# RUN adduser -u 8080 --disabled-password --gecos "" exchange-rate && chown -R exchange-rate /app
# USER exchange-rate 

CMD ["gunicorn", "config.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "--access-logfile", "./gunicorn-access.log", "--bind", "0.0.0.0:8000"]