# Generated by Django 4.0.5 on 2022-07-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_currency_watchlist_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
