# Generated by Django 4.0.5 on 2022-08-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_refresh_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
