# Generated by Django 3.2.13 on 2022-04-20 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangerate",
            name="call_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="환율 호출 시간"
            ),
            preserve_default=False,
        ),
    ]
