# Generated by Django 3.2.13 on 2022-04-21 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rate", "0002_exchangerate_call_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangerate",
            name="call_date",
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="fix_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="환율 갱신 시간"
            ),
            preserve_default=False,
        ),
    ]
