# Generated by Django 3.2.13 on 2022-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rate", "0003_auto_20220421_0938"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRateSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("day_off", models.DateField(verbose_name="쉬는 날")),
                ("memo", models.TextField(verbose_name="메모")),
            ],
            options={
                "db_table": "exchange_rate_schedule",
                "ordering": [],
            },
        ),
    ]
