# Generated by Django 3.2.13 on 2022-04-23 10:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0005_alter_exchangerateschedule_memo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='exchangerate',
            managers=[
                ('asyncs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='exchangerateschedule',
            managers=[
                ('asyncs', django.db.models.manager.Manager()),
            ],
        ),
    ]
