# Generated by Django 3.2.13 on 2022-04-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0006_auto_20220423_1944'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='exchangerate',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='exchangerateschedule',
            managers=[
            ],
        ),
    ]
