# Generated by Django 3.2.13 on 2022-05-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rate", "0008_auto_20220502_2139"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exchangerate",
            old_name="sales_rate",
            new_name="standard_price",
        ),
    ]
