# Generated by Django 3.2.13 on 2022-05-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0010_exchangerate_country_alter_exchangerate_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['created_at']},
        ),
    ]
