# Generated by Django 4.0.4 on 2022-06-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0013_exchangeratelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
