# Generated by Django 4.0.4 on 2022-06-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rate", "0014_delete_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangeratelist",
            name="country",
            field=models.CharField(max_length=25, verbose_name="국가"),
        ),
        migrations.AlterField(
            model_name="exchangeratelist",
            name="currency",
            field=models.CharField(max_length=25, verbose_name="통화명"),
        ),
    ]
