# Generated by Django 4.0.4 on 2022-06-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rate", "0015_alter_exchangeratelist_country_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="exchangeratelist",
            table="exchangeRateList",
        ),
    ]
