# Generated by Django 4.0.4 on 2022-06-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0017_exchangeratelist_currency_kr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeratelist',
            old_name='currency',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='exchangeratelist',
            old_name='currency_kr',
            new_name='name_kr',
        ),
        migrations.RenameField(
            model_name='exchangeratelist',
            old_name='price_base',
            new_name='standard_price',
        ),
        migrations.AlterModelTable(
            name='exchangeratelist',
            table='country',
        ),
    ]
