# Generated by Django 4.0.4 on 2022-06-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0018_rename_currency_exchangeratelist_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangeRateList',
            new_name='Country',
        ),
    ]
