# Generated by Django 3.2.13 on 2022-06-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rate", "0019_rename_exchangeratelist_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=25, verbose_name="통화 단위"),
        ),
        migrations.AlterField(
            model_name="country",
            name="name_kr",
            field=models.CharField(
                default="null", max_length=25, verbose_name="한글 통화 단위"
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="currency",
            field=models.CharField(default="None", max_length=25, verbose_name="통화 단위"),
        ),
    ]
